module.exports = {
  apps: [
    {
      name: 'classifieds-frontend',
      script: 'node_modules/next/dist/bin/next',
      args: 'start -p 3000',
      cwd: './',
      instances: 'max',
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      env_development: {
        NODE_ENV: 'development',
        PORT: 3000,
      },
      max_memory_restart: '500M',
      error_file: './logs/frontend-error.log',
      out_file: './logs/frontend-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      watch: false,
      max_restarts: 10,
      restart_delay: 5000,
      kill_timeout: 10000,
    },
    {
      name: 'classifieds-socket',
      script: 'socket-server.js',
      cwd: './',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        SOCKET_PORT: 3006,
        CORS_ORIGIN: '*',
      },
      env_development: {
        NODE_ENV: 'development',
        SOCKET_PORT: 3006,
        CORS_ORIGIN: '*',
      },
      max_memory_restart: '200M',
      error_file: './logs/socket-error.log',
      out_file: './logs/socket-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      watch: false,
      max_restarts: 10,
      restart_delay: 3000,
      kill_timeout: 10000,
      autorestart: true,
    },
  ],
};
