<?php

namespace Database\Seeders;

use App\Models\ProductImageMap;
use Illuminate\Database\Seeder;

class ProductImageMapSeeder extends Seeder
{
    public function run(): void
    {
        $mappings = [
            ['keyword' => 'iphone 13 pro max', 'image_path' => 'ads/iphone-13-pro-max.jpg'],
            ['keyword' => 'iphone 13 pro', 'image_path' => 'ads/iphone-13-pro.jpg'],
            ['keyword' => 'iphone 13', 'image_path' => 'ads/iphone-13.jpg'],
            ['keyword' => 'iphone 12 pro max', 'image_path' => 'ads/iphone-12-pro-max.jpg'],
            ['keyword' => 'iphone 12', 'image_path' => 'ads/iphone-12.jpg'],
            ['keyword' => 'iphone 11 pro max', 'image_path' => 'ads/iphone-11-pro-max.jpg'],
            ['keyword' => 'iphone 11', 'image_path' => 'ads/iphone-11.jpg'],
            ['keyword' => 'iphone x', 'image_path' => 'ads/iphone-x.jpg'],
            ['keyword' => 'samsung galaxy s21', 'image_path' => 'ads/samsung-galaxy-s21.jpg'],
            ['keyword' => 'samsung galaxy s22', 'image_path' => 'ads/samsung-galaxy-s22.jpg'],
            ['keyword' => 'samsung galaxy s23', 'image_path' => 'ads/samsung-galaxy-s23.jpg'],
            ['keyword' => 'samsung galaxy note 20', 'image_path' => 'ads/samsung-galaxy-note-20.jpg'],
            ['keyword' => 'toyota camry 2010', 'image_path' => 'ads/toyota-camry-2010.jpg'],
            ['keyword' => 'toyota camry 2015', 'image_path' => 'ads/toyota-camry-2015.jpg'],
            ['keyword' => 'toyota camry 2020', 'image_path' => 'ads/toyota-camry-2020.jpg'],
            ['keyword' => 'toyota corolla 2010', 'image_path' => 'ads/toyota-corolla-2010.jpg'],
            ['keyword' => 'toyota corolla 2015', 'image_path' => 'ads/toyota-corolla-2015.jpg'],
            ['keyword' => 'toyota hilux', 'image_path' => 'ads/toyota-hilux.jpg'],
            ['keyword' => 'toyota rav4', 'image_path' => 'ads/toyota-rav4.jpg'],
            ['keyword' => 'honda accord', 'image_path' => 'ads/honda-accord.jpg'],
            ['keyword' => 'honda civic', 'image_path' => 'ads/honda-civic.jpg'],
            ['keyword' => 'lexus rx 350', 'image_path' => 'ads/lexus-rx-350.jpg'],
            ['keyword' => 'mercedes benz c300', 'image_path' => 'ads/mercedes-benz-c300.jpg'],
            ['keyword' => 'bmw 3 series', 'image_path' => 'ads/bmw-3-series.jpg'],
            ['keyword' => 'hyundai sonata', 'image_path' => 'ads/hyundai-sonata.jpg'],
            ['keyword' => 'kia optima', 'image_path' => 'ads/kia-optima.jpg'],
            ['keyword' => 'hp laptop', 'image_path' => 'ads/hp-laptop.jpg'],
            ['keyword' => 'dell laptop', 'image_path' => 'ads/dell-laptop.jpg'],
            ['keyword' => 'macbook pro', 'image_path' => 'ads/macbook-pro.jpg'],
            ['keyword' => 'macbook air', 'image_path' => 'ads/macbook-air.jpg'],
            ['keyword' => 'lenovo laptop', 'image_path' => 'ads/lenovo-laptop.jpg'],
            ['keyword' => 'asus laptop', 'image_path' => 'ads/asus-laptop.jpg'],
            ['keyword' => 'acer laptop', 'image_path' => 'ads/acer-laptop.jpg'],
            ['keyword' => 'samsung tv', 'image_path' => 'ads/samsung-tv.jpg'],
            ['keyword' => 'lg tv', 'image_path' => 'ads/lg-tv.jpg'],
            ['keyword' => 'sony tv', 'image_path' => 'ads/sony-tv.jpg'],
            ['keyword' => 'panasonic tv', 'image_path' => 'ads/panasonic-tv.jpg'],
            ['keyword' => 'apple watch', 'image_path' => 'ads/apple-watch.jpg'],
            ['keyword' => 'samsung watch', 'image_path' => 'ads/samsung-watch.jpg'],
            ['keyword' => 'airpods pro', 'image_path' => 'ads/airpods-pro.jpg'],
            ['keyword' => 'airpods', 'image_path' => 'ads/airpods.jpg'],
            ['keyword' => 'ps5', 'image_path' => 'ads/ps5.jpg'],
            ['keyword' => 'playstation 5', 'image_path' => 'ads/ps5.jpg'],
            ['keyword' => 'xbox series x', 'image_path' => 'ads/xbox-series-x.jpg'],
            ['keyword' => 'nintendo switch', 'image_path' => 'ads/nintendo-switch.jpg'],
            ['keyword' => 'canon camera', 'image_path' => 'ads/canon-camera.jpg'],
            ['keyword' => 'nikon camera', 'image_path' => 'ads/nikon-camera.jpg'],
            ['keyword' => 'sony camera', 'image_path' => 'ads/sony-camera.jpg'],
            ['keyword' => 'iphone 14 pro max', 'image_path' => 'ads/iphone-14-pro-max.jpg'],
            ['keyword' => 'iphone 14 pro', 'image_path' => 'ads/iphone-14-pro.jpg'],
            ['keyword' => 'iphone 14', 'image_path' => 'ads/iphone-14.jpg'],
            ['keyword' => 'iphone 15 pro max', 'image_path' => 'ads/iphone-15-pro-max.jpg'],
            ['keyword' => 'iphone 15 pro', 'image_path' => 'ads/iphone-15-pro.jpg'],
            ['keyword' => 'iphone 15', 'image_path' => 'ads/iphone-15.jpg'],
            ['keyword' => 'infinix phone', 'image_path' => 'ads/infinix-phone.jpg'],
            ['keyword' => 'tecno phone', 'image_path' => 'ads/tecno-phone.jpg'],
            ['keyword' => 'samsung phone', 'image_path' => 'ads/samsung-phone.jpg'],
            ['keyword' => 'oppo phone', 'image_path' => 'ads/oppo-phone.jpg'],
            ['keyword' => 'vivo phone', 'image_path' => 'ads/vivo-phone.jpg'],
            ['keyword' => 'nokia phone', 'image_path' => 'ads/nokia-phone.jpg'],
            ['keyword' => 'huawei phone', 'image_path' => 'ads/huawei-phone.jpg'],
            ['keyword' => 'itel phone', 'image_path' => 'ads/itel-phone.jpg'],
            ['keyword' => 'tablets', 'image_path' => 'ads/tablets.jpg'],
            ['keyword' => 'ipad', 'image_path' => 'ads/ipad.jpg'],
            ['keyword' => 'generator', 'image_path' => 'ads/generator.jpg'],
            ['keyword' => 'inverter', 'image_path' => 'ads/inverter.jpg'],
            ['keyword' => 'solar panel', 'image_path' => 'ads/solar-panel.jpg'],
            ['keyword' => 'ac', 'image_path' => 'ads/ac.jpg'],
            ['keyword' => 'air conditioner', 'image_path' => 'ads/ac.jpg'],
            ['keyword' => 'refrigerator', 'image_path' => 'ads/refrigerator.jpg'],
            ['keyword' => 'freezer', 'image_path' => 'ads/freezer.jpg'],
            ['keyword' => 'washing machine', 'image_path' => 'ads/washing-machine.jpg'],
            ['keyword' => 'microwave', 'image_path' => 'ads/microwave.jpg'],
            ['keyword' => 'electric iron', 'image_path' => 'ads/electric-iron.jpg'],
            ['keyword' => 'blender', 'image_path' => 'ads/blender.jpg'],
            ['keyword' => 'standing fan', 'image_path' => 'ads/standing-fan.jpg'],
            ['keyword' => 'ceiling fan', 'image_path' => 'ads/ceiling-fan.jpg'],
            ['keyword' => 'power bank', 'image_path' => 'ads/power-bank.jpg'],
            ['keyword' => 'chair', 'image_path' => 'ads/chair.jpg'],
            ['keyword' => 'sofa', 'image_path' => 'ads/sofa.jpg'],
            ['keyword' => 'dining table', 'image_path' => 'ads/dining-table.jpg'],
            ['keyword' => 'bed', 'image_path' => 'ads/bed.jpg'],
            ['keyword' => 'wardrobe', 'image_path' => 'ads/wardrobe.jpg'],
            ['keyword' => 'television', 'image_path' => 'ads/television.jpg'],
            ['keyword' => 'music system', 'image_path' => 'ads/music-system.jpg'],
            ['keyword' => 'speaker', 'image_path' => 'ads/speaker.jpg'],
            ['keyword' => 'guitar', 'image_path' => 'ads/guitar.jpg'],
            ['keyword' => 'drum', 'image_path' => 'ads/drum.jpg'],
            ['keyword' => 'piano', 'image_path' => 'ads/piano.jpg'],
            ['keyword' => 'bicycle', 'image_path' => 'ads/bicycle.jpg'],
            ['keyword' => 'gym equipment', 'image_path' => 'ads/gym-equipment.jpg'],
            ['keyword' => 'treadmill', 'image_path' => 'ads/treadmill.jpg'],
            ['keyword' => 'dog', 'image_path' => 'ads/dog.jpg'],
            ['keyword' => 'cat', 'image_path' => 'ads/cat.jpg'],
            ['keyword' => 'puppy', 'image_path' => 'ads/puppy.jpg'],
            ['keyword' => 'kitten', 'image_path' => 'ads/kitten.jpg'],
            ['keyword' => 'bird', 'image_path' => 'ads/bird.jpg'],
            ['keyword' => 'fish', 'image_path' => 'ads/fish.jpg'],
            ['keyword' => 'gold ring', 'image_path' => 'ads/gold-ring.jpg'],
            ['keyword' => 'necklace', 'image_path' => 'ads/necklace.jpg'],
            ['keyword' => 'bracelet', 'image_path' => 'ads/bracelet.jpg'],
            ['keyword' => 'earring', 'image_path' => 'ads/earring.jpg'],
            ['keyword' => 'wedding ring', 'image_path' => 'ads/wedding-ring.jpg'],
            ['keyword' => 'watch', 'image_path' => 'ads/watch.jpg'],
            ['keyword' => 'men watch', 'image_path' => 'ads/men-watch.jpg'],
            ['keyword' => 'women watch', 'image_path' => 'ads/women-watch.jpg'],
            ['keyword' => 'bag', 'image_path' => 'ads/bag.jpg'],
            ['keyword' => 'handbag', 'image_path' => 'ads/handbag.jpg'],
            ['keyword' => 'backpack', 'image_path' => 'ads/backpack.jpg'],
            ['keyword' => 'shoe', 'image_path' => 'ads/shoe.jpg'],
            ['keyword' => 'sneaker', 'image_path' => 'ads/sneaker.jpg'],
            ['keyword' => 'heel', 'image_path' => 'ads/heel.jpg'],
            ['keyword' => 'boot', 'image_path' => 'ads/boot.jpg'],
            ['keyword' => 'shirt', 'image_path' => 'ads/shirt.jpg'],
            ['keyword' => 'trouser', 'image_path' => 'ads/trouser.jpg'],
            ['keyword' => 'jean', 'image_path' => 'ads/jean.jpg'],
            ['keyword' => 'dress', 'image_path' => 'ads/dress.jpg'],
            ['keyword' => 'agbada', 'image_path' => 'ads/agbada.jpg'],
            ['keyword' => 'native', 'image_path' => 'ads/native.jpg'],
            ['keyword' => 'kitchen', 'image_path' => 'ads/kitchen.jpg'],
            ['keyword' => 'plot', 'image_path' => 'ads/plot.jpg'],
            ['keyword' => 'land', 'image_path' => 'ads/land.jpg'],
            ['keyword' => 'house', 'image_path' => 'ads/house.jpg'],
            ['keyword' => 'apartment', 'image_path' => 'ads/apartment.jpg'],
            ['keyword' => 'flat', 'image_path' => 'ads/flat.jpg'],
            ['keyword' => 'shop', 'image_path' => 'ads/shop.jpg'],
            ['keyword' => 'warehouse', 'image_path' => 'ads/warehouse.jpg'],
            ['keyword' => 'office', 'image_path' => 'ads/office.jpg'],
            ['keyword' => 'building', 'image_path' => 'ads/building.jpg'],
            ['keyword' => 'bicycle', 'image_path' => 'ads/bicycle.jpg'],
            ['keyword' => 'motorcycle', 'image_path' => 'ads/motorcycle.jpg'],
            ['keyword' => 'bus', 'image_path' => 'ads/bus.jpg'],
            ['keyword' => 'truck', 'image_path' => 'ads/truck.jpg'],
            ['keyword' => 'tractor', 'image_path' => 'ads/tractor.jpg'],
        ];

        foreach ($mappings as $mapping) {
            ProductImageMap::updateOrCreate(
                ['keyword' => $mapping['keyword']],
                ['image_path' => $mapping['image_path']]
            );
        }
    }
}
