export const BRAND = {
  name: 'iList',
  logo: 'https://classified-ads-nu.vercel.app/icons/iList-white.png',
  logoDark: 'https://classified-ads-nu.vercel.app/icons/iList-dark.png',
  website: 'https://classified-ads-nu.vercel.app',
  supportEmail: 'support@ilist.ng',
  supportUrl: 'https://classified-ads-nu.vercel.app/help',
  twitter: 'https://x.com/ilist_ng',
  instagram: 'https://instagram.com/ilist.ng',
  address: 'Lagos, Nigeria',
  copyright: `© ${new Date().getFullYear()} iList. All rights reserved.`,
} as const;

export const COLORS = {
  primary: '#16a34a',
  primaryDark: '#15803d',
  primaryLight: '#dcfce7',
  success: '#16a34a',
  successLight: '#dcfce7',
  warning: '#f97316',
  warningLight: '#ffedd5',
  error: '#dc2626',
  errorLight: '#fee2e2',
  gray: {
    50: '#f9fafb',
    100: '#f3f4f6',
    200: '#e5e7eb',
    300: '#d1d5db',
    400: '#9ca3af',
    500: '#6b7280',
    600: '#4b5563',
    700: '#374151',
    800: '#1f2937',
    900: '#111827',
  },
  white: '#ffffff',
  bg: '#f5f7fa',
  cardBg: '#ffffff',
  text: '#111827',
  textSecondary: '#6b7280',
} as const;
