export { default as EmailLayout } from './components/EmailLayout';
export { default as EmailHeader } from './components/EmailHeader';
export { default as EmailFooter } from './components/EmailFooter';
export { default as CTAButton } from './components/CTAButton';
export { default as StatusBadge } from './components/StatusBadge';
export { default as SectionCard } from './components/SectionCard';
export { default as InfoRow } from './components/InfoRow';
export { default as Divider } from './components/Divider';
export { default as ProductCard } from './components/ProductCard';
export { default as ReceiptTable } from './components/ReceiptTable';
export { default as SecurityNotice } from './components/SecurityNotice';

export { default as Welcome } from './templates/auth/Welcome';
export { default as EmailVerification } from './templates/auth/EmailVerification';
export { default as OtpEmail } from './templates/auth/OtpEmail';
export { default as PasswordReset } from './templates/auth/PasswordReset';
export { default as PasswordChanged } from './templates/auth/PasswordChanged';
export { default as LoginAlert } from './templates/auth/LoginAlert';
export { default as AdPosted } from './templates/marketplace/AdPosted';
export { default as AdApproved } from './templates/marketplace/AdApproved';
export { default as AdRejected } from './templates/marketplace/AdRejected';
export { default as AdExpired } from './templates/marketplace/AdExpired';
export { default as AdBoosted } from './templates/marketplace/AdBoosted';
export { default as BoostExpiring } from './templates/marketplace/BoostExpiring';
export { default as PaymentReceipt } from './templates/marketplace/PaymentReceipt';
export { default as WalletFunded } from './templates/marketplace/WalletFunded';
export { default as WithdrawalSuccessful } from './templates/marketplace/WithdrawalSuccessful';
export { default as NewMessage } from './templates/messaging/NewMessage';
export { default as SellerReply } from './templates/messaging/SellerReply';
export { default as ReportReceived } from './templates/admin/ReportReceived';
export { default as AccountWarning } from './templates/admin/AccountWarning';
export { default as VerificationStatus } from './templates/admin/VerificationStatus';

export { sendEmail } from './utils/send';
export * from './utils/types';
